# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
